### ISSUE TITLE
Frontiers Numeric Style

### ISSUE THREAD

**Issue by adam3smith** [citation-style-language/styles#1642]
It looks like Frontiers now has a numeric style in addition to the author-date one we already have
http://www.frontiersin.org/about/AuthorGuidelines#_References
we should support it and see which journals it applies to exactly.

**Comment by zuphilip** [comment]
We have already some more independent styles here:
 * Frontiers journals (author-date style)
 * Frontiers medical journals (numeric paranthesis style)
 * Frontiers in Ecology and the Environment (author-date style)
 * Frontiers in Optics (numeric bracket style)
 * Frontiers in Physics (numeric bracket style)

Actually, as far as I understand the section in the author guidelines, there should be three different styles:
 * author-date
 * numeric in paranthesis
 * numeric in brackets

Maybe it would be a good starting point to receive a new list from the publisher, because [our current one](https://github.com/citation-style-language/utilities/blob/master/generate_dependent_styles/data/frontiers/_README.mdown) is 1,5 year old. What do you think @rmzelle @adam3smith ?

**Comment by rmzelle** [comment]
I asked the production office for a new list.

**Comment by rmzelle** [comment]
I just received a new list (from production.office (at) frontiersin.org):

[List of Field Journals.xlsx](https://github.com/citation-style-language/styles/files/77271/List.of.Field.Journals.xlsx)

**Comment by zuphilip** [comment]
Okay, it looks that
 * Health --> `frontiers-medical-journals`
 * Science --> `frontiers` most of the times, but sometimes also with square brackets and otherwise like medical journals (e.g. [Frontiers in Physics](http://journal.frontiersin.org/article/10.3389/fphy.2016.00010/abstract))

**Comment by rmzelle** [comment]
@damnation333, do you think we can close this now?

**Comment by damnation333** [comment]
Yes. Absolutely. :)
