### ISSUE TITLE
Journal of Hip Preserving Surgery 

### ISSUE THREAD

**Issue by adam3smith** [citation-style-language/styles#1717]
https://forums.zotero.org/discussion/37265/style-request-journal-of-hip-preserving-surgery/#Item_4

Guidelines for authors: http://www.oxfordjournals.org/our_journals/jhps/for_authors/manuscript_instructions.html

Online ISSN 2054-8397 

I just realized that it should be a comparable style like Clinical Orthopeadics and Related Research (CORR).

With the following changes:

1. truncated page numbers, i.e. type 345-9
2. For references with >4 authors, the first 3 authors should be listed, followed by et al.
3. Numbered in order of appearance
4. The journal should be written like that: Arch Orthop Trauma Surg. and not like that: Arch. Orthop. Trauma Surg.

**Comment by zuphilip** [comment]
CORR does not seem to exist as a CSL style and it is published by Springer. Thus, I don't think this helps us here. However, the style `oxford-university-press-scimed-numeric` does look pretty close and it is from the same publisher in the same field (medicine). However, there seem to be some difficulties, e.g. the volume number should be bold. But the style guide seems not very consistent... I will have to look closer...

**Comment by zuphilip** [comment]
Well, current articles from this journal are actually writing the volume number bold and do also otherwise look "the same" as the above mentioned `oxford-university-press-scimed-numeric`-style. No space or a space before and after volume number is not consistent through different articles. Thus, I guess they are not that picky about it these spaces. Therefore, I will generate a dependent style. If we have better information we can always improve on that.

**Comment by adam3smith** [comment]
yeah, makes sense to me.
