### ISSUE TITLE
Error in ferdinand-porsche-fern-fachhochschule.csl (follow-up to issue #1846)

### ISSUE THREAD

**Issue by christian-focke-mail-fernfh-ac-at** [citation-style-language/styles#1849]
In the bibliography, the year is printed "(, yyyy)" instead of "(yyyy)". This has to be due to one of the modifications Sebastian Karcher proposed to me during his review yesterday. Unfortunately, I am not a CSL expert myself, so all the modifications he proposed made sense to me and I implemented them all right away. -- Can anybody help with this issue?

**Comment by christian-focke-mail-fernfh-ac-at** [comment]
Sorry -- the error is only in the preview in the Zotero Style Repository.

**Comment by rmzelle** [comment]
@dstillman, it looks like the preview of https://www.zotero.org/styles?q=ferdinand hasn't updated since https://github.com/citation-style-language/styles/commit/fa37571f867c9c13389c0cf025aad5c7f5961632 three hours ago (the style source is up to date). The previous commit, https://github.com/citation-style-language/styles-distribution/commit/b7deca6534bb3ace93c0cd92d587751c8666d27b, did come through.

**Comment by rmzelle** [comment]
@dstillman, preview is up to date now.

**Comment by adam3smith** [comment]
(my recollection was that previews can take up to 24hs to generate/update)

**Comment by dstillman** [comment]
4 hours, but I've just made some changes to trigger preview updates as well on commit. (At some point we'll optimize it to regenerate just the necessary previews, but for now it regenerates them all, so it will take a few minutes each time.)

**Comment by rmzelle** [comment]
Thanks Dan. Somehow I thought it was already supposed to update within the hour. Quite a few style contributors check the previews after style updates, so this is much appreciated!
