### ISSUE TITLE
Add new style Create universite-laval-departement-des-sciences-historiques-french-canada.csl

### ISSUE THREAD

**Issue by CharlesQc** [citation-style-language/styles#2027]
Hi,

I just created a style to match Universite Laval - Departement des sciences historiques and would like it added to the repository. The file is not based on a particular style, as it was coded from scratch. Name is chosen to fit other Universite Laval's files in the repository., but differs significantly in some ways. It is french.

I pulled the request and merged it to the main branch (probably should not have done that, since as I have read, it should be done by someone else after verification) I apologize for any inconvenience. 

https://github.com/CharlesQc/styles/pull/1

Thanks!

CharlesQc

**Comment by rmzelle** [comment]
Thanks!

Could you follow the instructions for "submitting a new style" at https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md. You currently haven't actually submitted a contribution to our repository, but only to your own copy of it.

(and when you do, just use "universite-laval-departement-des-sciences-historiques.csl" instead of "universite-laval-departement-des-sciences-historiques-french-canada.csl", with matching style ID and "self" link)

**Comment by CharlesQc** [comment]
Thanks for the tips! I just created the pull request in the repository, and changed both ID and "self" link.

**Comment by rmzelle** [comment]
Continued in #2028.
