### ISSUE TITLE
Chicago Illustrations CSL is ostensibly incorrect

### ISSUE THREAD

**Issue by dsifford** [citation-style-language/styles#2196]
CC: @alexwatkins 

Hi there,

I think the CSL might be incorrect for `chicago-figures.csl`.

![image](https://cloud.githubusercontent.com/assets/5240018/18191498/03b8eb16-7099-11e6-851e-1dac5baffc32.png)

I'm aware that the style isn't _supposed_ to render a bibliography, however there are other styles that similarly do not render bibliographies, and do not create this issue. For example, the most recent style added to this repo: [mercatus-center.csl](https://github.com/citation-style-language/styles/blob/master/mercatus-center.csl).

I'm fairly certain just removing [these lines](https://github.com/citation-style-language/styles/blob/master/chicago-figures.csl#L32-L69) will fix this error (but I'm certainly no expert with CSL XML, so I'll leave that for the group to decide on)

**Edit:** Tried the above in the CSL code editor and it just duplicated the inline citations, so chock that one as a 'no'. I'm totally unskilled with CSL, so I'll leave it to you experts to school me on 😄 

It's not a huge deal as-is, but the issue in my case (a citeproc-js user) is: Having bibliography fields set causes citeproc to call somewhere in the ballpark of 20-40 individual function calls (including recursion loops) before eventually returning an error, which is much slower in comparison to what happens with `mercatus-center.csl`.

Thanks so much for everyone's work on this 😄

**Comment by alexwatkins** [comment]
I'm certainly no CSL expert, it does render bibliography entries but only
for images and book sections (so that you can cite an image from a book
such as a frontispiece). Since the example bibliography doesn't include
those two as examples it just says there's no printed form. That's what I
was going for here,but welcome any fixes that make it work better!

-Alex

**Comment by rmzelle** [comment]
The Mercatus Center CSL style is a "note" style, and for that type of citation format bibliographies are often optional, since the (foot)notes (rendered by `<citation/>`) are usually pretty elaborate, and enough to locate the cited item. 

This is typically not the case for "in-text" CSL styles. In-text citations are usually pretty sparse (e.g. "(fig. 1)" doesn't tell you anything about the item), so for these styles the bibliography is pretty much required.

It looks like the CSL spec just says the the bibliography is optional, but it's just rather nonsensical for in-text styles, so it's not too surprising citeproc-js throws an error.

**Comment by rmzelle** [comment]
@dsifford, are you just raising this issue because you're working on the CSL editor? You're not actually interested in using this style, right?

People who use this style actually need the bibliography. A better fix would be to change the style so that it outputs at least something for item types other than chapter and graphic. (the double `<choose/>` is also unnecessary, since CSL has `<else>` and `<else-if>` options)

**Comment by dsifford** [comment]
> it does render bibliography entries but only for images and book sections

Ah, didn't realize that. I think the style is probably correct then. Not sure there's really any other way to go about it for what's needed.

@rmzelle Thanks for the clarification! Sorry for creating a stir here. Still very much dipping my toes in the CSL pool.

> it's not too surprising citeproc-js throws an error.

Nope, I wasn't concerned really about the error, but rather how long it took for the processor to _realize_ that it's not a valid bibliography. I'll perhaps chat it over with @fbennett and/or send in a PR to that repo if I can figure out a way to improve that.

Thanks again, gents!

**Comment by dsifford** [comment]
@rmzelle 

> are you just raising this issue because you're working on the CSL editor? You're not actually interested in using this style, right?

Nope, not interested in it personally. I'm the developer for [this wordpress plugin](https://github.com/dsifford/academic-bloggers-toolkit) and while messing around with some things this evening i randomly picked that style and it threw an exception that I wasn't yet aware of.

> People who use this style actually need the bibliography. A better fix would be to change the style so that it outputs at least something for item types other than chapter and graphic. (the double <choose/> is also unnecessary, since CSL has <else> and <else-if> options)

^^ Love that idea. Would the output for those other items just be the same as Chicago 16th proper? Any idea @alexwatkins ?

**Comment by rmzelle** [comment]
> Would the output for those other items just be the same as Chicago 16th proper?

Well, it's neither simple to incorporate this style into Chicago proper, or to add full Chicago support to this version (especially since the "chapter" item type is used for figures here). But just printing e.g. the authors, date, and title for non-figure items would result in some output for the majority for items. It doesn't have to look particularly good, but it would prevent the citeproc-js errors, and might help people who accidentally cited a non-figure item (since it would be much clearer which non-figure item they cited).

**Comment by dsifford** [comment]
@rmzelle Good points.

And now that I think of it, it actually makes sense why @fbennett 's function takes so long to error: Depending on the citation type, one or more of the citations within the collection may still resolve without issues.

For some reason I thought that if one error was thrown, the collection I would receive from the processor would be 

```js
[
    '[CSL STYLE ERROR: reference with no printed form.]',
    '[CSL STYLE ERROR: reference with no printed form.]',
    '[CSL STYLE ERROR: reference with no printed form.]',
[
```

when in all actuality, it could very well be 

```js
[
    '[CSL STYLE ERROR: reference with no printed form.]',
    // some valid image citation here
    '[CSL STYLE ERROR: reference with no printed form.]',
[
```

@fbennett : 1
me : 0

I think it's clear that I need to get some rest! 😣 

Thanks again for the enlightening discussion @rmzelle! This issue is probably good to call "closed", unless you need it open for whatever reason. 👍
