### ISSUE TITLE
Explicit copyright

### ISSUE THREAD

**Issue by koppor** [citation-style-language/styles#2372]
I aim to support getting the CSL styles packaged for debian so that they are available for [JabRef ](https://www.jabref.org/). Debian pays attention that the authors of contributions are properly attributed.

The README.md of this repository contains a license statement. However, there is no AUTHOR information. For instance, https://github.com/citation-style-language/styles/blob/master/acs-nano.csl does not state who authored it. On http://citationstyles.org/, there is the `Default copyright text`.

Would it be possible to explicitly state the copyright holders somehow? In JabRef, we use [a script](https://github.com/JabRef/jabref/blob/master/scripts/generate-authors.sh) to automatically generate the authors including a [mapping](https://github.com/JabRef/jabref/blob/master/.mailmap) of committer names.

Would it be possible to state the copyright explicitly and add an AUTHORS file?

**Comment by adam3smith** [comment]
I'm not sure how well we can do this automatically since Rintze and I add a lot of styles for other people. But we do try to pay close attention to having some type of authoring information in new styles, and ACS Nano slipped through (my bad, in this case). Have you run a script to find all styles without an author or should we do that?

**Comment by rmzelle** [comment]
> Would it be possible to state the copyright explicitly and add an AUTHORS file?

You're only concerned about the copyright on the styles, right? IANAL, but all our styles are licensed under CC-BY-SA. That's not enough? I'm not sure they're even copyright-able.

As for an AUTHORS file, that seems like a headache to keep up to date, since we have rolling releases and do most of the pull request merging straight on GitHub. Does Debian specify their requirements explicitly somewhere?

(also note that to keep things tidier, we actually encourage people to strip the original authors/contributors from styles when they create a derived version, and just point back to the original style as the template: https://github.com/citation-style-language/styles/wiki/Style-Requirements#8---template-link)

**Comment by adam3smith** [comment]
> but all our styles are licensed under CC-BY-SA
I take it the BY part is the problem if you don't know who to attribute to?

**Comment by rmzelle** [comment]
> I take it the BY part is the problem if you don't know who to attribute to?

I wrote up my thoughts of how downstream users of our CC-BY-SA styles should acknowledge the project/styles at https://github.com/citation-style-language/styles/blob/master/README.md#licensing. Where styles are missing authors/contributors, at least the git log provides a paper trail.

**Comment by gregoa** [comment]
Some hints for Debian can be found at https://wiki.debian.org/UpstreamGuide#Licenses and https://ftp-master.debian.org/REJECT-FAQ.html (the "license in each file" is not a requirement though).

Basically to be able to say "These files are released under <license>" we need to have someone who says it and has the right to do so, a.k.a. a copyright holder. A license without a natural or legal entity who can give the rights in the license is a bit difficult :)

https://github.com/citation-style-language/styles/blob/master/README.md#licensing says "must include a clear mention of the CSL project" -- does this mean "mention the CSL project as the copyright holder" or "Copyright 20xx CSL project" or something else? (Side question: Can the CSL project hold the copyright, i.e. is it a legal entity?)

A list of authors is purely optional from a Debian point of view, as authors are not necessarily copyright holders (and vice versa).

Cheers,
gregor, Debian Developer

**Comment by adam3smith** [comment]
no, CSL is not a legal entity, so can't hold copyright. The copyright holder should be the author listed in the style -- hence my question: how many styles without an author do we actually have? (And I assume you've noted that every CSL file already constains a link to the license)

**Comment by gregoa** [comment]
Ok, thanks for the clarification. And yes, the license situation is excellent at first glance, thanks for that.

As for the number of files with and without `<author>` tags:

```
% grep -r -l '<author>' * | wc -l 
1401
% grep -r -L '<author>' * | wc -l 
7003
```

I guess digging up authors/copyright holders for 7003 files is not going to fly. Neither is mentioning 8404 files/people for the `debian/copyright` file we'd need to write. Hrm.

Cheers,
gregor

**Comment by adam3smith** [comment]
don't include the dependent sub-folder: those are dependent styles which contain only metadata and no original work whatsoever and are as such not copyrighteable. See https://github.com/citation-style-language/styles/blob/master/dependent/3-biotech.csl for an example, but they all look like this.

**Comment by gregoa** [comment]
Ah, ok. - That makes the situation much better:
```
% grep -l '<author>' *.csl | wc -l
1348
% grep -L '<author>' *.csl | wc -l
42
```

**Comment by adam3smith** [comment]
OK, we can probably fix that based on commit history & template links. Do you agree @rmzelle ?

**Comment by rmzelle** [comment]
The actual number might be even lower, since some styles will have a "contributor" but not an "author" (we have two roles for small and large contributions, respectively, but we don't really police proper assignment, as there is a large grey area in their distinction).

@gregoa, would you be all set if we make sure all styles have at least one author/contributor listed? As @adam3smith mentioned, CSL is just a (loosely) organized open source project. We are not part of any legal entity, and the spirit of the project is definitively to share as much as possible (code is typically under MIT, documentation/styles/locales under CC-BY-SA).

**Comment by rmzelle** [comment]
I used `grep -E -L '(<author>|<contributor>)' *.csl` to check for independent styles without an author or contributor, and added authors (mostly based on the Git history) to those that popped up: https://github.com/citation-style-language/styles/commit/01a42789bd2806107e1089c2b6b0c339c7a092fa

**Comment by gregoa** [comment]
On Tue, 20 Dec 2016 10:06:41 -0800, Rintze M. Zelle wrote:

> @gregoa, would you be all set if we make sure all styles have at
> least one author/contributor listed? As @adam3smith mentioned, CSL
> is just a (loosely) organized open source project. We are not part
> of any legal entity, and the spirit of the project is definitively
> to share as much as possible (code is typically under MIT,
> documentation/styles/locales under CC-BY-SA).

Yeah, I guess we can work from that.

This still requires someone to write a script to extract the
information and then the ftp-masters to accept the package but this
all sounds possible. 

Thanks you very much for adding the missing pieces so quickly and for
all your explanations!


Cheers,
gregor

-- 
 .''`.  https://info.comodo.priv.at/ - Debian Developer https://www.debian.org
 : :' : OpenPGP fingerprint D1E1 316E 93A7 60A8 104D  85FA BB3A 6801 8649 AA06
 `. `'  Member of VIBE!AT & SPI, fellow of the Free Software Foundation Europe
   `-   NP: Rolling Stones: Street Fighting Man

**Comment by rmzelle** [comment]
> This still requires someone to write a script to extract the information and then the ftp-masters to accept the package but this all sounds possible.

By the way, if possible, I'd prefer to host such a script in https://github.com/citation-style-language/utilities instead of in the "styles" and "locales" repositories. And per above, as volunteer maintainers, we'd strongly prefer a solution that doesn't require us to continuously keep an AUTHORS file up to date. Would it be possible to generate it downstream of us?

**Comment by gregoa** [comment]
On Sat, 24 Dec 2016 10:31:42 -0800, Rintze M. Zelle wrote:

> > This still requires someone to write a script to extract the
> > information and then the ftp-masters to accept the package but
> > this all sounds possible.
> 
> By the way, if possible, I'd prefer to host such a script in
> https://github.com/citation-style-language/utilities instead of in
> the "styles" and "locales" repositories. And per above, as
> volunteer maintainers, we'd strongly prefer a solution that doesn't
> require us to continuously keep an AUTHORS file up to date. Would
> it be possible to generate it downstream of us?

Sure, sorry for being unclear. I meant someone on the Debian side has
to write a script to transform the information into a form used in
Debian and maintain the script in the Debian package. Thanks to your
work of adding the information to the csl files, we can do the rest
on our own without needing to put even more burden on you.

/*

As a side note, https://github.com/citation-style-language/utilities
contains a LICENSE.txt which says "Copyright (c) 2015 Citation Style
Language"; that kind of surprises me :)

*/


Cheers,
gregor 

-- 
 .''`.  https://info.comodo.priv.at/ - Debian Developer https://www.debian.org
 : :' : OpenPGP fingerprint D1E1 316E 93A7 60A8 104D  85FA BB3A 6801 8649 AA06
 `. `'  Member of VIBE!AT & SPI, fellow of the Free Software Foundation Europe
   `-   NP: Red Hot Chili Peppers: Fortune Faded

**Comment by rmzelle** [comment]
> As a side note, https://github.com/citation-style-language/utilities contains a LICENSE.txt which says "Copyright (c) 2015 Citation Style Language"; that kind of surprises me :)

That copyright statement is part of GitHub's MIT license template: http://choosealicense.com/licenses/mit/.
