### ISSUE TITLE
Best practices & enforcement for match attributes

### ISSUE THREAD

**Issue by adam3smith** [citation-style-language/styles#2412]
See https://github.com/citation-style-language/styles/pull/2407#discussion_r95100995
match attributes on a choose condition with a single variable/type are unnecessary: with a single variable, `any` and `all` are equivalent. The question is whether we should aim to minimize their occurrence to keep code neat, or whether we're fine with them, as they may help to prevent coding errors (by relying on defaults -- in this case `all`). If the former, we could probably remove these with a regex search. If the latter, obviously nothing to do. 
FWIW, there are thousands of instances.

**Comment by rmzelle** [comment]
Do we know if there is a main reason we have so many? It is because the Visual Editor spits out the attribute no matter what? Or because of manual edits? (I searched the commit history, and only found https://github.com/citation-style-language/styles/commit/b55a9c1704b74a35e9aa522dc4e67dc632146781 and https://github.com/citation-style-language/styles/commit/532217b02629a7dc4f91113f7dddbf458e1c9e80 as mass commits, which shouldn't have contributed)

I have no strong feelings either way. Styles would be more compact and easier to read without the redundant element, but then again, people might assume `match="any"` when extending conditionals and run into bugs.

**Comment by adam3smith** [comment]
I think we should just remain agnostic about this; doesn't really matter either way and I don't think there's a strong reason to enforce this in either direction.

**Comment by rmzelle** [comment]
Fine with me.
