### ISSUE TITLE
Two tweaks to first-monday.csl: remove ":" after "accessed" and use brackets rather than superscripts

### ISSUE THREAD

**Issue by reagle** [citation-style-language/styles#3231]
I just went through the publication process and note the editor made two changes to my bibliography. 

The first is that there is no colon after "accessed" and before the date. This is easily remedied by changing [the ": " suffix](https://github.com/citation-style-language/styles/blob/master/first-monday.csl#L58).

The second is to use a bracket (e.g., "[1]") rather than superscripted numeral. I'm not sure how to do that yet, but I'm sure it can be done.

**Comment by reagle** [comment]
I'm sorry, the second issue is for footnotes, which is outside the ambit of CSL. I'll leave it in the comment because FM style is very weird and requires notes when there is pagination. That is, the following is required to create a parenthetical citation and then include the same citation with the page number in a footnote with a bracket rather than superscript designation.

```
[@McArthur2009dsg].^[@McArthur2009dsg, p. 62]
```

**Comment by rmzelle** [comment]
> required to create a parenthetical citation and then include the same citation with the page number in a footnote with a bracket rather than superscript designation.
>
> ```
> [@McArthur2009dsg].^[@McArthur2009dsg, p. 62]
> ```

I'm not a 100% I follow what this is supposed to look like, but your example looks like a "label" style (http://docs.citationstyles.org/en/stable/primer.html#label-styles), but in CSL 1.0.1 those are in-text styles like author-date (with a bibliography at the end), not note styles like what you seem to be describing here. Is there a PDF anywhere that shows what this style is supposed to look like in print?

> I have to use the redundant note, and I'm not sure how to get that to be [1] rather than ^1^.

Per http://docs.citationstyles.org/en/stable/primer.html#note-styles, in CSL 1.0.1 the foot/endnote markers are defined outside of CSL (e.g. by your word processor). Are you using pandoc, or some other writing tool?

**Comment by reagle** [comment]
I'm using pandoc. Here is an [example of the style](http://firstmonday.org/ojs/index.php/fm/article/view/8054/6585), you can see parenthetical and numeric notes in brackets where the page numbers appear.

This is an admittedly weird style and I don't want the second issue to overshadow a quick fix to access's unneeded colon.

**Comment by rmzelle** [comment]
> a quick fix to access's unneeded colon.

Should be fixed now.

> Here is an example of the style, you can see parenthetical and numeric notes in brackets where the page numbers appear.

Yeah, that's a bit odd. I guess most styles just put the page number information in the parenthetical in-text author-date cite (e.g. "(McCoy, 2013, pp. 312–316)"), instead of using an entirely extra set of notes. Safe to say, CSL doesn't support this currently. CSL styles are either author-date or note, and you can't have both systems in a single document.

@adam3smith, have you ever seen anything like this? It looks like the journal uses an author-date style, but any locator information is expected in separate footnotes. Very weird.

**Comment by rmzelle** [comment]
> The second is to use a bracket (e.g., "[1]") rather than superscripted numeral. I'm not sure how to do that yet, but I'm sure it can be done.

Given that you're using pandoc, https://stackoverflow.com/questions/40213184/how-can-i-alter-the-formatting-of-pandoc-footnote-marks seems relevant. They suggest just applying overriding CSS to add the square brackets. You'd just need an additional rule to remove the superscript.

**Comment by reagle** [comment]
@rmzelle, thanks for the fix, and yes, I'll have to make use of various hacks to deal with this weird style. Thanks for the suggestions.

**Comment by rmzelle** [comment]
> I'll have to make use of various hacks to deal with this weird style

I think you could do it with two separate CSL styles, since the two types of citation don't seem very interconnected, but you'd first have to finish the manuscript with one style (e.g. the author-date one), convert the citations to plain-text, and then use the second style (e.g. the note one). Not sure that's doable with pandoc. And you'd have to make sure that all the items cited with the note style are also cited with the author-date style.
