### ISSUE TITLE
Chicago-author-date does not title-case journal articles

### ISSUE THREAD

**Issue by jasonjensen** [citation-style-language/styles#3306]
The chicago-author-date style applies title case to all container/collection titles except for journal titles. I was going to submit a pull request to fix this, but though I would ask first whether there was any particular reason for this?

**Comment by adam3smith** [comment]
It's tricky -- there are, especially in the humanities, a fair number of journals with non-English names even though they publish in English. That means title casing would produce bizarre titles -- and since you do need the title casing for the titles, you can't disable it using language. 

So I generally recommend storing journals in title case, even though that does go against US cataloging standards, afaik. Not entirely sure what to do about that absent a more complex (and likely too complex) data model.

**Comment by jasonjensen** [comment]
That makes sense. Thanks for explaining.
