### ISSUE TITLE
Style request: analytical chemistry

### ISSUE THREAD

**Issue by DimitriF** [citation-style-language/styles#3439]
Hello,
I used the american-chemical-society.csl for the journal analytical chemistry and was told that the issue number should not appear for journal articles.
I saw several ACS style having there own csl file in dependent, could it be the case for analytical chemistry?
here are the guideline:
http://pubs.acs.org/paragonplus/submission/ancham/ancham_authguide.pdf
from american-chemical-society.csl  only line 153 must be removed to do so, I can make a pull request.
Thanks
Dimitri

**Comment by DimitriF** [comment]
I should have mention, editor comment is about references in the Supporting Information that do not follow the same editing path.

**Comment by rmzelle** [comment]
@DimitriF, ACS has standardized on a single citation style, and this style requires the issue number for some special cases that CSL styles can't identify and which cannot easily be automated (such as journals that restart page numbering for each issue). For that reason we always include the issue number to err on the side of including more information than requested, instead of too little.

See #3850 for more details, and the text under "Publication Volume Field" in the ACS style guide (https://pubs.acs.org/doi/pdf/10.1021/bk-2006-STYG.ch014, page 296). Ideally the editors of Analytical Chemistry would be more permissive concerning supplementary information. Otherwise you'll just have to edit those references by hand to remove the issues for articles that don't need them.
