### ISSUE TITLE
ABNT - Too Much same Standard

### ISSUE THREAD

**Issue by jobdiogenes** [citation-style-language/styles#3440]
There's too much ABNT Styles, need only one. 
If perhaps same institution has their own as derivative (which I doubt), they must name as another name.
I guess that instead correct the issues, some people get one,make changes and submit as new.

In current situation, users can't know what is the really correct ABNT style. 
My vote is join all contributors to effort to make only one updated to last version. 
I think the best approach  is create and update a Metadata for the ABNT format, in a way that style could be generated automatically. 

And important  express what version (Number/Year) will support, as new ABNT version come and updates are made, style change, and only last version will be available.
 
I'm offer to help to manage this effort, talking with contributors, create and manage repository for the style, or better the Metadata. I could also code. 

Could someone give me the contacts of all contributors for each ABNT style here.?

Thanks

**Comment by adam3smith** [comment]
Style authors are listed in styles, typically with their e-mail addresses and otherwise accessible through the style history via github. I'd have to dig them out the same way.

> In current situation, users can't know what is the really correct ABNT style.

I'd dispute that. There are two styles clearly labeled 
Associação Brasileira de Normas Técnicas (note, Portuguese - Brazil)
Associação Brasileira de Normas Técnicas (Portuguese - Brazil)

All other ABNT variant start with the naming of the university/institution supporting it. My understanding is that such variants are common and that ABNT is used to identify them locally, i.e. is an important label for the styles. The way they're displayed conforms to CSL's  general practice for similar situations (e.g. Vancouver, Harvard), so we won't change that. If there are people willing to consolidate their institutions' styles that's great, but I'm not going to twist any arms on this.

Updating the two main versions would be terrific and I'd be happy for the style titles to include version numbers.
