### ISSUE TITLE
How can i use depend folder CSL for biblography..?

### ISSUE THREAD

**Issue by subhamsuthar** [citation-style-language/styles#4325]
I didn't find how to use depends folder csl.

**Comment by POBrien333** [comment]
You don't need to "use" it as an enduser of Zotero.
To explain what these dependent styles are.
Imagine the publishing house Springer. They have dozens of journals. But instead of them having a style for each one they actually have about 15 "house styles" in various formats. They all have a name like springer-vancouver.csl etc. So a generic name.
Now for example the Springer journal "The Review of Black Political Economy" just uses that springer-vancouver.csl style automatically if you select it in Zotero. You don't have to do anything. Zotero will just download the correct style for you.

**Comment by adam3smith** [comment]
Closing as this isn't a bug/feature request. Feel free to follow up with further questions.
