### ISSUE TITLE
Ampersand in apa.csl

### ISSUE THREAD

**Issue by pkup10** [citation-style-language/styles#4651]
In APA 7 there should an ampersand in in-text citations with parenthesis and he word "and" in in-text citations without parenthesis, is there a way to do that in this style? I am looking at the file apa.csl.

Thanks.
Peter

**Comment by samueldodson** [comment]
See #3748.

**Comment by adam3smith** [comment]
Thanks @samueldodson for digging up the relevant ticket. Closing here (FWIW, we may eventually amend CSL to add a separate out-of-parentheses (or whatever we'll call it) format, but, not any time soon. Since this is quite particular to APA style, more likely in the short term, reference managers may just pull citations out of the parentheses and add a replacement rule for APA and APA-based styles. I know that's what Bookends (not using CSL) does already and I think that's what Zotero is considering

**Comment by bwiernik** [comment]
This issue can probably be closed at this point?
