### ISSUE TITLE
`bibtex.csl` breaks with space in author last name

### ISSUE THREAD

**Issue by rschuetzler** [citation-style-language/styles#4753]
The generation of the `citeKey` in `bibtex.csl` creates an invalid key if there are spaces in the authors last name. For example, the following, as you can see, creates the cite key of `van de Schoot_Yerkes_Mouw_Sonneveld_2013`, and spaces in the key break parsing.

```
@article{van de Schoot_Yerkes_Mouw_Sonneveld_2013, 
title={What Took Them So Long? Explaining PhD Delays among Doctoral Candidates}, 
volume={8}, 
ISSN={1932-6203}, 
url={https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3720867/}, 
DOI={10.1371/journal.pone.0068839}, 
number={7}, 
journal={PLoS ONE}, 
author={van de Schoot, Rens and Yerkes, Mara A. and Mouw, Jolien M. and Sonneveld, Hans}, 
year={2013}, 
month={Jul} 
}
```

**Comment by adam3smith** [comment]
Nothing we can do about this -- CSL doesn't allow modifying strings. For this and other reasons we don't recommend relying on CSL to generate bibtex. Personally I'd prefer to just remove the style altogether, but since some people find it useful, we're leaving it on the repository. 
FWIW, we'll likely get a citekey variable in CSL in the future that'd solve this particular problem.

**Comment by woutermont** [comment]
> Nothing we can do about this -- CSL doesn't allow modifying strings. 

I'd like to reopen this issue, since I believe that "CSL doesn't allow modifying strings" is not enough reason to conclude that there is "nothing we can do about this." There might be other possibilities of circumventing this small but annoying issue in a style that otherwise works quite fine.

> FWIW, we'll likely get a citekey variable in CSL in the future that'd solve this particular problem.

Might I propose that, at least pending a dedicated citekey variable, we use an already existing variable which might be suited to the purpose? One example that comes to mind is the `citation-label` variable: it is not yet used by the bibtex style, and could therefore be employed as a preferred way to set the bibtex citekey (only when it is available, for compatibility purposes).

Pending your consideration, I'll create a pull request.
