### ISSUE TITLE
APA 7th edition seems incorrect

### ISSUE THREAD

**Issue by Dreamsorcerer** [citation-style-language/styles#5121]
Below is an example of formatting a citation with the apa.csl file. This doesn't seem to match the style as shown at: https://apastyle.apa.org/instructional-aids/reference-guide.pdf
For example, the journal name appears twice.

The citation is created with the citeproc-py library in Python. I'm assuming there is something wrong with the style, but maybe there is an issue with how citeproc-py is parsing it?

<img width="708" alt="Screen Shot 2020-11-23 at 4 34 24 pm" src="https://user-images.githubusercontent.com/2203121/99988837-e3d45b00-2da9-11eb-9345-40442eb13fe2.png">

**Comment by adam3smith** [comment]
This is generated with incorrect data (conference proceeding instead of journal article) and there seem to be issues with citeproc-py as well (the double-period shouldn't exist). Here's what the style produces using Zotero/citeproc-js and correct data:

Ward, R. D., Zemlak, T. S., Innes, B. H., Last, P. R., & Hebert, P. D. N. (2005). DNA barcoding Australia’s fish species. _Philosophical Transactions of the Royal Society B: Biological Sciences_, _360_(1462), 1847–1857. https://doi.org/10.1098/rstb.2005.1716

**Comment by Dreamsorcerer** [comment]
Thanks a lot, seems the main issue is that everything was getting labelled as 'article' instead of 'article-journal'.
