### ISSUE TITLE
DOI isn't being handled by vancouver.csl

### ISSUE THREAD

**Issue by Vitaliy-1** [citation-style-language/styles#5122]
[vancouver](https://github.com/citation-style-language/styles/blob/master/vancouver.csl) stylesheet doesn't fully correspond to the most recent [NLM recommendations](http://www.nlm.nih.gov/bsd/uniform_requirements.html) mentioned in its `info` part. In particular, DOI as well as other identifiers, like PMID and PMCID, which are also added to the CSL specifications (https://github.com/citation-style-language/schema/issues/87) aren't being managed by it.

NLM in those samples refers to the more detailed description in "National Information Standards Organization [NISO Z39.29-2005 (R2010)](https://www.niso.org/publications/ansiniso-z3929-2005-r2010) Bibliographic References", on which the recommendations are based. Indeed, it contains such a description:

> 3.2.7 Numbers and Other Numeric and Alphanumeric Identifiers
> ...
> All numeric or alphanumeric strings used as identifiers appear in the Notes group, with the
> exception of volume and issue numbers, the number of a meeting, or the patent number.
> The Notes group includes identifiers such as ISBN, ISSN, CODEN, grant number, contract
> number, technical report number, DOI, URL, etc. Any such identifier is preceded by its
> descriptive designation and a colon, with the number recorded exactly as it appears on the
> piece, e.g., “ISBN: 1-55798-243-0,” “Contract No.: PHS-HSM-110-72-325,” or
> “DOI: 10.1017/S0021853703008491."

Another example of DOI/PMID can be found in the NLM citation style guide: https://www.ncbi.nlm.nih.gov/books/NBK7282/#A32751

**Comment by adam3smith** [comment]
No, this is a misreading of _Citing Medicine_. DOIs and other identifiers are optional -- the examples your link to are listed in the sub-chapter "Notes for Journal Articles **(optional)**" -- and in fact, many of the example citations in the journal article chapter are to articles that do have PM(C)IDs and DOIs and do not have them included in citations. I think our Vancouver style represents the modal interpretation of the norms.

We do have several other styles that included DOIs and/or PM(C)IDs and follow _Citing Medicine_ otherwise, so people who want them have options available.
