### ISSUE TITLE
MDPI Template issues

### ISSUE THREAD

**Issue by einsweniger** [citation-style-language/styles#5127]
Hello everybody,

we recently submitted to MDPI and used the CSL provided here, and some issues surfaced.
I'm referencing Version 5 of the Style guide, available through https://www.mdpi.com/authors/references or directly https://res.mdpi.com/data/mdpi_references_guide_v5.pdf

This line says there were no updates past the date, which is wrong.
https://github.com/citation-style-language/styles/blob/d4176ca79fdb87ec144a2dcd65466402023eaf4f/multidisciplinary-digital-publishing-institute.csl#L19

The dates in v5 are ordered as `day month year` with only space as a seperator (c.f. page 6)
https://github.com/citation-style-language/styles/blob/d4176ca79fdb87ec144a2dcd65466402023eaf4f/multidisciplinary-digital-publishing-institute.csl#L72-L78

The proceedings should as well be formatted with a full date (c.f. page 6), but are not:
https://github.com/citation-style-language/styles/blob/d4176ca79fdb87ec144a2dcd65466402023eaf4f/multidisciplinary-digital-publishing-institute.csl#L176

Website access date is also not formatted as `day month year` (see page 7). The example also gives the long form instead of the short, which is used here
https://github.com/citation-style-language/styles/blob/d4176ca79fdb87ec144a2dcd65466402023eaf4f/multidisciplinary-digital-publishing-institute.csl#L193-L197

We're using the template through pandoc citeproc, so i'm not sure it this is an issue related to the template.
We had to litter `text-case="title"` throughout many of the `title`/`container-title` attributes, otherwise they were converted to only capitalizing the first word of the conference or titles, which the MDPI editorial seems to disagree with, so this point is up for discussion.

pinging @todoricMDPI @rmzelle and @POBrien333 since they seem to be maintaining this.

regards,
-1

**Comment by adam3smith** [comment]
Thanks -- the dates should be an easy fix. PRs welcome if you're interested.

> We had to litter text-case="title" throughout many of the title/container-title attributes, otherwise they were converted to only capitalizing the first word of the conference or titles, which the MDPI editorial seems to disagree with, so this point is up for discussion.

That's likely a byproduct of using Bib(La)TeX somewhere in the process (which isn't necessary). In the absence of `text-case`, CSL processors leave item casing as is. Since BibTeX's convention are exactly the opposite of CSLs, converting back and forth can sometimes cause issues.

**Comment by adam3smith** [comment]
> This line says there were no updates past the date, which is wrong.

The update dates on `/styles` aren't updated automatically and we don't enforce updating on commit since it's too error prone to do manually. The actual update date can either be found in the commit history or in the distribution repository. They're also reflected in Zotero's listing of the styles at zotero.org/styles

**Comment by einsweniger** [comment]
I'll gladly create a PR, but I'd rather have @todoricMDPI have a say about the text casing.
I'd rather not have to send another bad version into review :D

**Comment by adam3smith** [comment]
My best interpretation of the style guide is that book titles (including proceeding titles) should indeed be in title case, but article and chapter titles should be sentence case (i.e. without `text-case` attribute in the CSL)

**Comment by rordi** [comment]
Hi all, 

I am representing MDPI. Darko asked me to investigate and respond to the issues raised here.

I confirm that date format as mentioned @einsweniger is correct: ```day month year```as in:
- 3 February 2020
- 12 December 1956

I also want to confirm that titles should be capitalised for all types of title (article title, book titles, conference names, journal names, etc.); i.e. the CSL for MDPI should *not* attempt to lowercase titles.

Currently published papers on mdpi.com use both - lowercased and capitalised titles. Likely this is caused by MDPI production editors actually actively using the CSL for some of MDPI journals... Though, I am puzzled why an author has to discover this issue, as the MDPI CSL is used daily by hundreds of production editors here at MDPI.

We will also update the MDPI Reference Guide accordingly soon.

**Comment by einsweniger** [comment]
Thank you for clearing this up.
Is it possible to give a head's up here, when you've published the new reference?
It would also be fine with me, if someone from MDPI made the PR instead of me.
What would you recommend  @rordi?
