### ISSUE TITLE
Update pull request

### ISSUE THREAD

**Issue by lsaadaoui** [citation-style-language/styles#5128]
How can we make the changes that you suggest ? When I click the "Files changed" tab of my pull request, I don't find the ellipsis button to edit my file. The file dosen't even exist in "Files changed". May you please help ?

**Comment by rmzelle** [comment]
> How can we make the changes that you suggest ? When I click the "Files changed" tab of my pull request, I don't find the ellipsis button to edit my file. The file dosen't even exist in "Files changed". May you please help ?

@lsaadaoui. you deleted the NPSS style from your pull request on November 22nd, so that's why "Files changed" was empty. I just put the latest version back: https://github.com/citation-style-language/styles/pull/5063/commits.

Let continue our conversation at https://github.com/citation-style-language/styles/pull/5063.
