### ISSUE TITLE
APA 7th (American Psychological Association), First Author's First Initial(s) Missing

### ISSUE THREAD

**Issue by gtreneman** [citation-style-language/styles#5722]
I think the title gets at the heart of it.
We're using this file in our library's discovery system, and the generated citation is missing the first author's first initial(s):
![citation-issue](https://user-images.githubusercontent.com/49755986/141362796-8fc7a5a9-f012-42cd-9870-07262a12edc0.png)

**Comment by adam3smith** [comment]
The CSL style obviously does that correctly as you can see checking Zotero, zbib, Mendeley, etc. (there isn't even a way to somehow omit first Name or initials just for the first author in CSL.)
I'd check if the problem also occurs in other styles like Chicago, in which case it's likely due to the data passes to the citation generator. If it's only for APA, that'd indicate a bug somewhere deeper in the discovery catalog's CSL implementation.

**Comment by gtreneman** [comment]
Thanks for the explanation, adam3smith! I appreciate the help.
