### ISSUE TITLE
APA 6- Missing Initial for First Author

### ISSUE THREAD

**Issue by bgBond** [citation-style-language/styles#5908]
I have for example an article with the given data-
Higham, John.; Krieger, Leonard.; Gilbert, Felix, 1905-1991.

Why is APA 6 citation missing the "J" letter from John?

  Higham, Krieger, L., & Gilbert, F. (1965). History. Prentice-Hall.

MLA looks correct-

  Higham, John., Leonard. Krieger, and Felix Gilbert. History. Englewood Cliffs, N.J: Prentice-Hall, 1965. Print.

**Comment by bwiernik** [comment]
This is on Ex Libris correct? There is some sort of bug with the way it serves APA styles that its developers need to correct

**Comment by bgBond** [comment]
Thanks, can you please elaborate what may be the problem?
All other styles work perfectly with authors names (includes the first one), only APA 6 has this behavior , and I can see the full name is sent in all cases.

**Comment by bwiernik** [comment]
The style is written to include the intial for the first author. You can see that this style works correctly by looking at the previews on https://Zotero.org/styles or using https://zbib.org

You are seeing this issue in Ex Libris, correct? Or is it some other platform? If so, which?

Assuming it's Ex Libris, This is a problem you need to report to Ex Libris, not us. I believe the last time this issue was raised to us here, the problem was that the version of Ex Libris was using a version of the CSL citation processor, citeproc-js, that was several years of out of date. Please update your Ex Libris version to the latest version and/or raise the issue with them.

**Comment by bgBond** [comment]
You are correct, thank!

**Comment by bwiernik** [comment]
I believe that's the case
