### ISSUE TITLE
New style for a higher education school

### ISSUE THREAD

**Issue by hum84** [citation-style-language/styles#5944]
Hi there!

I would like to create a citation style which can be use from my students. There are some styles on zotero which are quite similar, but I change some brackets. Now I will save this style to zotero and make visible for the students. But it doesen`t work.

Can you help me?

**Comment by bwiernik** [comment]
You would need to either submit the edited CSL file to the repository here (https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md) or distribute the file directly to your students. 

On another note, though, is there a particular reason you are making a custom style, rather than using one of the widely adopted style manuals, such as APA, Chicago, MLA, Vancouver, or NLM?

**Comment by hum84** [comment]
Thanks for your fast answer. I searched for a style that fits our school recommendations. This one Taylor & Francis - Vancouver/National Library of Medicine is the best to fit, but we need it with other brackets and in german. That`s why I was thinking to use our own created style.

**Comment by bwiernik** [comment]
Feel free to submit a pull request by following the instructions I linked to above.

**Comment by adam3smith** [comment]
PR is here already: https://github.com/citation-style-language/styles/pull/5943

Are the style requirements available online somewhere? That's a condition for including styles in the repository for Zotero et al.
I'd also encourage you to look at some other styles again. E.g. the three Vancouver (brackets styles https://www.zotero.org/styles?q=vancouver%20(brackets would all seem to meet you criteria and can be set to German.
