### ISSUE TITLE
more alphanumeric styles

### ISSUE THREAD

**Issue by kno10** [citation-style-language/styles#6440]
There appears to be only a single alphanumeric style, and it is "superseded":

[DIN 1505-2 (alphanumeric, Deutsch) - standard superseded by ISO-690](https://editor.citationstyles.org/styleInfo/?styleId=http%3A%2F%2Fwww.zotero.org%2Fstyles%2Fdin-1505-2-alphanumeric)

Is there a reason there is no style that closely mimics:
- Bibtex "[alpha](https://www.bibtex.com/s/bibliography-style-base-alpha/)"
- Biblatex "[alphabetic](https://de.overleaf.com/learn/latex/Biblatex_citation_styles)"

These style use *short* alphanumeric keys such as `[Exa02]` and `[AB02]` based on the last names and the year.

I still like these styles best, they are a decent trade-off of compactness and informativeness.

**Comment by adam3smith** [comment]
> There appears to be only a single alphanumeric style, and it is "superseded":

To be clear, the style isn't superseded (that's why we still have it up), DIN Norm 1505-2 is

CSL doesn't have any code that would allow different styling of these short forms (`citation-label` in CSL terms), and I don't think we're likely to add this to the spec. There are a tiny number of requests for this, and the only major styles requiring them are for Math journals that require LaTeX for submissions anyway. 

Technically it would be possible for any upstream implementation to allow users to configure citation-label (or for users to specify it in the YAML/JSON when using something like pandoc) and then have it be picked up by a CSL style that uses `citation-label`, but I'm not aware of any such efforts or major demand for that.

**Comment by bwiernik** [comment]
@adam3smith CSL 1.1.0 has syntax for customizing citation labels if that is adopted
