### ISSUE TITLE
German APA: Wrong in-text citation for sources by two authors: "&" instead of "und" (apa.csl)

### ISSUE THREAD

**Issue by gwbrck** [citation-style-language/styles#7018]
There appears to be an inconsistency in the German (lang="de") APA (apa.csl) citation style implementation regarding in-text citations for sources authored by two individuals.

Expected behavior:
Untersuchungen haben ergeben, dass … (Müller & Neuer, 2019).
Müller **und** Neuer (2019) schreiben, dass...

Current Behavior:
Untersuchungen haben ergeben, dass … (Müller & Neuer, 2019).
Müller **&** Neuer (2019) schreiben, dass 

I think there is no official German APA 7 style guide, other than the one from the Deutsche Gesellschaft für Psychologie. However, that is a different guide with its own CSL implementation. Therefore, I believe that the German APA 7 style should closely resemble the English version. Thus, the expected behavior mentioned above should reflect that.

I have also found evidence from three German-speaking universities that the expected behavior described above is being applied.

https://www.studium.ifp.uni-mainz.de/files/2020/12/APA7_Kurz-Manual.pdf p. 12
https://mediennutzung.uni-hohenheim.de/fileadmin/einrichtungen/mediennutzung/documents/Wissenschaftliches_Schreiben_nach_APA_7_20-10-2021.pdf p. 11 "Steiner und Xu (2020)".
https://www.uni-trier.de/fileadmin/fb2/MED/BAMA/Pruefungen/APA_7_Leitfaden_Medienwissenschaft_Stand_8.7.21.pdf chap. 2.5

**Comment by adam3smith** [comment]
CSL doesn't in its current version allow describing multiple in-text citation styles. It only defines the parenthetical version (Müller & Neuer, 2019) which as you note is correct. 
Some reference managers/tools (e.g., pandoc based tools) do allow users to create these citations, but that's outside of CSL's current scope (FWIW, I believe there's a LUA filter or so that'll fix this for pandoc).

We're aware of the ability to do this as a general desideratum and it's in the 1.1 spec draft.

**Comment by gwbrck** [comment]
Great, thank you for your quick response! I found issue #3748 and will follow up on it there.
