### ISSUE TITLE
Changed Harvard 7 Style (de) for Political Science

### ISSUE THREAD

**Issue by zasq** [citation-style-language/styles#74]
Hello!

I have changed the Harvard 7 Style (de) developed by Julian Onions and Sven Rothe to suit the needs for citing in Harvard style in German texts, especially in Political Science. Mainly, I changed the in-text citation style to [author year: page], avoiding the abbreviation for pages (S.) and changing the delimiters (no comma between author and year). For example: (Asbach 1999: 45) instead of (Asbach, 1999: S. 45) which is not the correct citing style in text for Political Science.

The style has been uploaded to:

git://gist.github.com/1546825.git

It might be interesting for others, as the in-text citation style meets the requirements of the "amerikanische Zitierweise" oder "Harvard Zitiersystem" (Harvard citation style in German) for theses in Political Science/Social Sciences. Is it possible to add it to the zotero style repository?

Thanks in advance!

Best,

Saskia Mestern

**Comment by mmoole** [comment]
aha, thanks to [the hint](https://github.com/citation-style-language/styles/pull/1697#issuecomment-142086163) from rmzelle I took again a look at the harvard7de style .. and since I did a bit of housekeeping lately, I found the source of all this evil :-) 
The harvard7de style was made according to a document dating back to 2002 that can be found at various locations, for example here:
http://qse.ifs.tuwien.ac.at/courses/Usability2/Literaturangaben.pdf
Yes, my professor told us to use this kind of style at that time (that was about 2007, at quite another university)..... 
As that would be to easy, I could not find the original source for this style document... But researching found out:
FHV: Fachhochschule Voralberg (the university name)
BM: could be anything, maybe an abbreviation for a study program... I didn't find something that makes sense.

So I went to their library site, and they even have a more recent document online:
http://www.fhv.at/media/pdf/bibliothek/schreibzentrum/leitfaden-wissenschaftlichen-arbeiten
Here they even talk about Zotero and do no more make 'one of a kind' things like flipping first name and family names of the authors in bibliography. They talk more generally of styles and do no more make such detailed specifications as in the document dating back to 2002. And they even have a style with their name 'Fachhochschule Voralberg' in the styles library at Zotero! :+1: 

So to conclude, I think this all comes down to how much the harvard7de style is used in reality. If there are lots of people using it, I think we should keep it, but maybe rename it to something like 'Harvard Fachhochschule Voralberg (archived)' or similar to express that it is outdated.
If the style isn't used at all, then let's delete it.
But from time to time I get emails (maybe 3 a year) from people that either have a fix or a question for the style. I guess this also comes from people looking for the 'generic' harvard style, and this looks like one..
What do you think? 
By the way, is there something like usage statistics for the styles? I think the downloads alone may be also interesting numbers, but usage would be actually more relevant for this question...

I hope that wasn't too much to read :-)

**Comment by rmzelle** [comment]
@mmoole, thanks for your sleuthing! I emailed Frank Weber from FHV, who contributed the https://github.com/citation-style-language/styles/blob/master/fachhochschule-vorarlberg.csl style. Maybe he can shed some light on the origin of that PDF.

**Comment by franklin66** [comment]
Hi Rintze, hi all,
Wow, this is interesting. Almost a bit like a detective story ;).
Well, let me think. I discovered Zotero during summer break 2008 and introduced it to some lecturers when the semester started. I started fiddling about with styles about March 2009. I picked the harvard7de-style because it was pretty close to what our guide for citations demanded.
The original contributors of the style I used were Julian Onions and Sven Rothe. 
I never realised that the documentation link had a connection to our university!
FHV stands for "Fachhochschule Vorarlberg", the german name of our university.
I am quite sure that "BM" stands for "Brigitte Mayer". She is a lecturer who teaches scientific writing and together with our head librarian she has been responsible for our FHV-guide for scientific writing for many years. But she didn't hear about Zotero before I introduced it to her in 2008, and the harvard7-style existed before that.
The URL of the documentation link shows us, that the guide somehow showed up on the servers of the "TU Wien" which is the Technical University of Vienna. The URL also shows us, that the document was used by the Institute for Quality Software Engineering, probably in a course about usabilty.

So maybe this is what happened: One of our professors (there are 2 or three that teach usablity at the FHV) gave a course at the TU Vienna - long before I had discovered Zotero. He asked his students to write a paper, demanding them to cite according to the guide he provided from the FHV.
Maybe Julian Onions and Sven Rothe were students in that course and developed the harvard7-style which I later found in the repository?
I will ask Mrs. Mayer about the document and I will also ask the professors. Maybe we can shed more light on this matter after this.
If the story I came up with is true or close to the truth I don't think a ot of people are using the style any more, as it isn't an "official" style of an institution. As regards the FHV we've been developping our own style and we're not using the harvard7-style.

I hope I could help,
Frank

**Comment by rmzelle** [comment]
Julian Onions contributed to many of the first few CSL styles, and his name might just have carried over from another style. I'm not sure about Sven Rothe.

It would be great if Mrs. Mayer could confirm she had a hand in writing the "Literaturangaben.pdf" PDF, and if she can tell whether this citation format has been superseded by the current format as used in https://github.com/citation-style-language/styles/blob/master/fachhochschule-vorarlberg.csl.

**Comment by mmoole** [comment]
Hi, yes, indeed, Julian was the creator of the style that this style is derived from. 
But my way to this style is as described above, more detailed: i was in a course where a professor gave us handouts that contained this document' contents. So at first I hunted down that very PDF that could serve as a real reference, and then was desperately searching for a name. Since it had to happen quickly I just added another harvard variant. I think there where about 3 or 4 at this time, in 2007 or 2008.  
I wonder if there are some statistics from zotero or the styles themselves...?

**Comment by franklin66** [comment]
Do you remember that professors name?

**Comment by franklin66** [comment]
I spoke with Prof. Mayer and it is one of her documents. She dates it back to 2002 or 2003, but she never had anything to do with the TU Vienna. So I'll ask two professores who might have taught at the TU Vienna.

**Comment by franklin66** [comment]
Ah - and yes, this format has been superseded by our current format.

**Comment by franklin66** [comment]
I spoke with the professors and one of them thinks, that this document found its way to the TU vienna via some PHD-Students; but its only an assumption. Anyway, I close the case here.

**Comment by adam3smith** [comment]
Given that we have an up-to-date FHV style now as well as a good number of German Harvard styles (including some pretty generic ones), I'm voting for removing the style at this point. If people are still using it, that's, if anything, an argument _for_ deleting it since they shouldn't be using a style based on a styleguide that's not in use anywhere anymore. @rmzelle if you agree, I'd prepare the PR

**Comment by rmzelle** [comment]
@adam3smith, yes, please. You'll redirect the style ID to the FHV style?

**Comment by mmoole** [comment]
I also agree since the style got quite old now 👍

**Comment by adam3smith** [comment]
OK, done. Thanks everyone.
